import { TourData } from './tour-types';

export const defaultTour: TourData = {
  id: 'tour-1',
  name: 'MIES 360',
  description: 'Recorrido virtual arquitectónico 360°',
  brandName: 'MIES 360',
  autoRotate: true,
  autoRotateSpeed: -2,
  showFloorPlan: true,
  showControls: true,
  scenes: [
    {
      id: 'scene-hallway',
      name: 'Entrada',
      panoramaUrl: '/panoramas/hallway.png',
      description: 'Hall de entrada principal',
      mapPosition: { x: 130, y: 120 },
      defaultView: { pitch: 0, yaw: 180, hfov: 75 },
      hotspots: [
        {
          id: 'hs-hall-living',
          pitch: 0,
          yaw: -30,
          type: 'scene',
          text: 'Ir a Sala de Estar',
          targetSceneId: 'scene-living',
          color: '#10b981',
          icon: 'arrow-right',
        },
        {
          id: 'hs-hall-bedroom',
          pitch: 0,
          yaw: 90,
          type: 'scene',
          text: 'Ir al Dormitorio',
          targetSceneId: 'scene-bedroom',
          color: '#10b981',
          icon: 'arrow-right',
        },
        {
          id: 'hs-hall-info',
          pitch: -5,
          yaw: 170,
          type: 'info',
          text: 'Bienvenido a MIES 360. Explore cada espacio de este proyecto arquitectónico con nuestro recorrido virtual inmersivo.',
          color: '#3b82f6',
          icon: 'info',
        },
      ],
    },
    {
      id: 'scene-living',
      name: 'Sala de Estar',
      panoramaUrl: '/panoramas/living-room.png',
      description: 'Amplia sala de estar con grandes ventanales',
      mapPosition: { x: 130, y: 55 },
      defaultView: { pitch: 0, yaw: 0, hfov: 75 },
      hotspots: [
        {
          id: 'hs-living-kitchen',
          pitch: 0,
          yaw: -60,
          type: 'scene',
          text: 'Ir a la Cocina',
          targetSceneId: 'scene-kitchen',
          color: '#10b981',
          icon: 'arrow-right',
        },
        {
          id: 'hs-living-terrace',
          pitch: 5,
          yaw: 30,
          type: 'scene',
          text: 'Ir a la Terraza',
          targetSceneId: 'scene-terrace',
          color: '#10b981',
          icon: 'arrow-right',
        },
        {
          id: 'hs-living-hall',
          pitch: 0,
          yaw: 160,
          type: 'scene',
          text: 'Volver a la Entrada',
          targetSceneId: 'scene-hallway',
          color: '#10b981',
          icon: 'arrow-right',
        },
        {
          id: 'hs-living-info',
          pitch: -10,
          yaw: -90,
          type: 'info',
          text: 'Sala de estar de 45m² con piso de madera natural y acabados de primera calidad.',
          color: '#3b82f6',
          icon: 'info',
        },
      ],
    },
    {
      id: 'scene-kitchen',
      name: 'Cocina',
      panoramaUrl: '/panoramas/kitchen.png',
      description: 'Cocina moderna con isla central',
      mapPosition: { x: 30, y: 55 },
      defaultView: { pitch: 0, yaw: 90, hfov: 75 },
      hotspots: [
        {
          id: 'hs-kitchen-living',
          pitch: 0,
          yaw: -120,
          type: 'scene',
          text: 'Ir a la Sala de Estar',
          targetSceneId: 'scene-living',
          color: '#10b981',
          icon: 'arrow-right',
        },
        {
          id: 'hs-kitchen-info',
          pitch: -5,
          yaw: 0,
          type: 'info',
          text: 'Cocina integral con isla de mármol, electrodomésticos de acero inoxidable y gabinetes de madera de nogal.',
          color: '#3b82f6',
          icon: 'info',
        },
      ],
    },
    {
      id: 'scene-bedroom',
      name: 'Dormitorio Principal',
      panoramaUrl: '/panoramas/bedroom.png',
      description: 'Dormitorio principal con vestidor',
      mapPosition: { x: 130, y: 185 },
      defaultView: { pitch: 0, yaw: 0, hfov: 75 },
      hotspots: [
        {
          id: 'hs-bedroom-bath',
          pitch: 0,
          yaw: -90,
          type: 'scene',
          text: 'Ir al Baño',
          targetSceneId: 'scene-bathroom',
          color: '#10b981',
          icon: 'arrow-right',
        },
        {
          id: 'hs-bedroom-hall',
          pitch: 0,
          yaw: 160,
          type: 'scene',
          text: 'Volver a la Entrada',
          targetSceneId: 'scene-hallway',
          color: '#10b981',
          icon: 'arrow-right',
        },
        {
          id: 'hs-bedroom-info',
          pitch: -8,
          yaw: 45,
          type: 'info',
          text: 'Dormitorio principal de 35m² con vestidor walk-in, baño en suite y vista a la terraza.',
          color: '#3b82f6',
          icon: 'info',
        },
      ],
    },
    {
      id: 'scene-bathroom',
      name: 'Baño Principal',
      panoramaUrl: '/panoramas/bathroom.png',
      description: 'Baño de lujo con acabados en mármol',
      mapPosition: { x: 230, y: 185 },
      defaultView: { pitch: 0, yaw: 90, hfov: 75 },
      hotspots: [
        {
          id: 'hs-bath-bedroom',
          pitch: 0,
          yaw: 90,
          type: 'scene',
          text: 'Volver al Dormitorio',
          targetSceneId: 'scene-bedroom',
          color: '#10b981',
          icon: 'arrow-right',
        },
        {
          id: 'hs-bath-info',
          pitch: -5,
          yaw: -45,
          type: 'info',
          text: 'Baño principal con bañera de diseño, ducha de cristal, doble lavamanos y acabados en mármol italiano.',
          color: '#3b82f6',
          icon: 'info',
        },
      ],
    },
    {
      id: 'scene-terrace',
      name: 'Terraza',
      panoramaUrl: '/panoramas/terrace.png',
      description: 'Terraza con vista panorámica a la ciudad',
      mapPosition: { x: 230, y: 55 },
      defaultView: { pitch: 5, yaw: 0, hfov: 90 },
      hotspots: [
        {
          id: 'hs-terrace-living',
          pitch: 0,
          yaw: 180,
          type: 'scene',
          text: 'Volver a la Sala',
          targetSceneId: 'scene-living',
          color: '#10b981',
          icon: 'arrow-right',
        },
        {
          id: 'hs-terrace-info',
          pitch: -15,
          yaw: 0,
          type: 'info',
          text: 'Terraza de 30m² con vista panorámica de 270° a la ciudad. Ideal para entretenimiento al aire libre.',
          color: '#3b82f6',
          icon: 'info',
        },
      ],
    },
  ],
  floorPlan: {
    width: 300,
    height: 260,
    bgColor: 'rgba(0, 0, 0, 0.7)',
    rooms: [
      {
        id: 'fp-hallway',
        sceneId: 'scene-hallway',
        name: 'Entrada',
        x: 100,
        y: 100,
        width: 70,
        height: 50,
        fillColor: 'rgba(255, 255, 255, 0.15)',
        strokeColor: 'rgba(255, 255, 255, 0.4)',
      },
      {
        id: 'fp-living',
        sceneId: 'scene-living',
        name: 'Sala',
        x: 90,
        y: 30,
        width: 90,
        height: 65,
        fillColor: 'rgba(255, 255, 255, 0.15)',
        strokeColor: 'rgba(255, 255, 255, 0.4)',
      },
      {
        id: 'fp-kitchen',
        sceneId: 'scene-kitchen',
        name: 'Cocina',
        x: 5,
        y: 25,
        width: 80,
        height: 65,
        fillColor: 'rgba(255, 255, 255, 0.15)',
        strokeColor: 'rgba(255, 255, 255, 0.4)',
      },
      {
        id: 'fp-bedroom',
        sceneId: 'scene-bedroom',
        name: 'Dorm.',
        x: 90,
        y: 165,
        width: 90,
        height: 55,
        fillColor: 'rgba(255, 255, 255, 0.15)',
        strokeColor: 'rgba(255, 255, 255, 0.4)',
      },
      {
        id: 'fp-bathroom',
        sceneId: 'scene-bathroom',
        name: 'Baño',
        x: 190,
        y: 165,
        width: 70,
        height: 55,
        fillColor: 'rgba(255, 255, 255, 0.15)',
        strokeColor: 'rgba(255, 255, 255, 0.4)',
      },
      {
        id: 'fp-terrace',
        sceneId: 'scene-terrace',
        name: 'Terraza',
        x: 190,
        y: 30,
        width: 75,
        height: 65,
        fillColor: 'rgba(255, 255, 255, 0.15)',
        strokeColor: 'rgba(255, 255, 255, 0.4)',
      },
    ],
    connections: [
      { from: 'fp-hallway', to: 'fp-living' },
      { from: 'fp-living', to: 'fp-kitchen' },
      { from: 'fp-living', to: 'fp-terrace' },
      { from: 'fp-hallway', to: 'fp-bedroom' },
      { from: 'fp-bedroom', to: 'fp-bathroom' },
    ],
  },
};
